
baseurl: "https://tractable-probabilistic-modeling.github.io/tpm2025/"
color-scheme: "#1a908e" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _papers

exclude:
  - .sass-cache

title: "8th Workshop on Tractable Probabilistic Modeling"
subtitle: "From Logic to Probabilities and Back"
conference: "[UAI 2025 Workshop](https://www.auai.org/uai2025/)"

shorttitle: "TPM Workshop @ UAI 2025"
information: "UAI 2025 Workshop on Tractable Probabilistic Modeling" 

organizers: "TPM 2025 Organizers"

deadlines:
  - item: Submission deadline
    date: June 2nd, 2025 <b><i>extended!</i></b>
  
  - item: Expected notification of acceptance
    date: June 18th, 2025

  - item: Camera-ready deadline
    date: July 14th, 2025 (Use the new <a href="/assets/tpm2025-template.zip">template</a>!)